apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-app
spec:
  selector:
    matchLabels:
      app: cloud-gateway-app
  template:
    metadata:
      labels:
        app: cloud-gateway-app
    spec:
      containers:
        - name: cloud-gateway-app
          image: mukeshkr24/gateway-service
          ports:
            - containerPort: 8760
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: config-cm
                  key: PORT
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: config-cm
                  key: ORDER_SERVICE_URL
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: config-cm
                  key: PAYMENT_SERVICE_URL
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: config-cm
                  key: PRODUCT_SERVICE_URL
            - name: CONFIG_URL
              valueFrom:
                configMapKeyRef:
                  name: config-cm
                  key: config_url

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  type: LoadBalancer
  selector:
    app: cloud-gateway-app
  ports:
    - port: 80
      targetPort: 8760
