apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-app
spec:
  selector:
    matchLabels:
      app: config-server-app
  template:
    metadata:
      labels:
        app: config-server-app
    spec:
      containers:
        - name: config-server-app
          image: mukeshkr24/config-server
          ports:
            - containerPort: 8765
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address

---
apiVersion: v1
kind: Service
metadata:
  name: config-service-svc
spec:
  selector:
    app: config-server-app
  ports:
    - port: 80
      targetPort: 8765
