apiVersion: v1
kind: Service
metadata:
  name: service-registry-svc
spec:
  selector:
    app: service-registry
  ports:
    - port: 80 # Port exposed on the service
      targetPort: 8761 # Port on the container
